{% set name = "prince" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2048aaa6ab2c738a17796a3f2ab669724db95fdc40dfcd004d6f9993dce1ee00

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - scikit-learn >=1.5.1
    - pandas >=2.2.0
    - altair >=5.0.0

test:
  imports:
    - prince
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # E   ModuleNotFoundError: No module named 'rpy2'
    # pytest tests

about:
  home: https://maxhalford.github.io/prince
  doc_url: https://maxhalford.github.io/prince
  dev_url: https://github.com/MaxHalford/prince
  summary: Multivariate exploratory data analysis in Python — PCA, CA, MCA, MFA, FAMD, GPA
  description: |
    Prince is a Python library for multivariate exploratory data analysis in Python.
    It includes a variety of methods for summarizing tabular data,
    including principal component analysis (PCA) and correspondence analysis (CA).
    Prince provides efficient implementations, using a scikit-learn API.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - skupr-anaconda
