{% set name = "prince" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prince-{{ version }}.tar.gz
  sha256: 3f60a30578ee9510f964069ab2a4d4f4c6f63711ea004783f7867f367b89c7d3

build:
  number: 1
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - poetry-core 1.5
    - pip
  run:
    - python
    - scikit-learn >=1.0.2,<2.0.0
    - pandas >=1.4.1,<3.0.0
    - altair >=4.2.2,<6.0.0

test:
  imports:
    - prince
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://maxhalford.github.io/prince/
  doc_url: https://maxhalford.github.io/prince/
  dev_url: https://github.com/MaxHalford/prince
  summary: Multivariate exploratory data analysis in Python — PCA, CA, MCA, MFA, FAMD, GPA
  description: |
    Prince is a Python library for multivariate exploratory data analysis in Python.
    It includes a variety of methods for summarizing tabular data,
    including principal component analysis (PCA) and correspondence analysis (CA).
    Prince provides efficient implementations, using a scikit-learn API.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - skupr-anaconda
