{% set name = "prince" %}
{% set version = "0.16.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ecd52e0c9a78ba173eb8b8b69fe8eb9ffe67f5db4fdbacf29e63af4ce330d8e2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - scikit-learn >=1.5.1,<2.0.0
    - pandas >=2.2.0,<3.0.0
    - altair >=5.0.0,<6.0.0

{% set ignore_tests = "" %}
# E   ModuleNotFoundError: No module named 'rpy2'
{% set ignore_tests = " --ignore=tests/some_test.py" %}  # [not (linux and x86_64)]
{% set ignore_tests = ignore_tests + " --ignore=tests/test_ca.py" %}  # [not (linux and x86_64)]
{% set ignore_tests = ignore_tests + " --ignore=tests/test_famd.py" %}  # [not (linux and x86_64)]
{% set ignore_tests = ignore_tests + " --ignore=tests/test_mca.py" %}  # [not (linux and x86_64)]
{% set ignore_tests = ignore_tests + " --ignore=tests/test_mfa.py" %}  # [not (linux and x86_64)]
{% set ignore_tests = ignore_tests + " --ignore=tests/test_pca.py" %}  # [not (linux and x86_64)]
{% set ignore_tests = ignore_tests + " --ignore=tests/test_svd.py" %}  # [not (linux and x86_64)]

test:
  source_files:
    - tests
  imports:
    - prince
  requires:
    - pip
    - pytest
    - xarray
    - rpy2  # [linux and x86_64]
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # rpy2 is not available on py312+ (available only on linux-64)
    - pytest tests {{ ignore_tests }}  # [py<312]

about:
  home: https://maxhalford.github.io/prince
  doc_url: https://maxhalford.github.io/prince
  dev_url: https://github.com/MaxHalford/prince
  summary: Multivariate exploratory data analysis in Python — PCA, CA, MCA, MFA, FAMD, GPA
  description: |
    Prince is a Python library for multivariate exploratory data analysis in Python.
    It includes a variety of methods for summarizing tabular data,
    including principal component analysis (PCA) and correspondence analysis (CA).
    Prince provides efficient implementations, using a scikit-learn API.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - skupr-anaconda
