{% set name = "prince" %}
{% set version = "0.10.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prince-{{ version }}.tar.gz
  sha256: 4f950fc06acb134954445887ef47ca86bf09c2fabe6e500bcad535326e45e6bf

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - poetry-core 1.5.1
    - pip
    - setuptools
    - wheel
  run:
    - python
    - scikit-learn >=1.0.2,<2.0.0
    - pandas >=1.4.1,<3.0.0
    - altair >=4.2.2,<6.0.0

test:
  imports:
    - prince
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://maxhalford.github.io/prince/
  doc_url: https://maxhalford.github.io/prince/
  dev_url: https://github.com/MaxHalford/prince
  summary: Multivariate exploratory data analysis in Python — PCA, CA, MCA, MFA, FAMD, GPA
  description: |
    Prince is a Python library for multivariate exploratory data analysis in Python. 
    It includes a variety of methods for summarizing tabular data, 
    including principal component analysis (PCA) and correspondence analysis (CA). 
    Prince provides efficient implementations, using a scikit-learn API.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - skupr-anaconda
